<?php

namespace AppBundle\Repository;

/**
 * ProductRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRep extends \Doctrine\ORM\EntityRepository
{
}