# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    console_command.test:
        class: AppBundle\Command\CsvImportCommand
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: console.command }
